CREATE TABLE USER (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    USERNAME TEXT,
    PASSWORD TEXT,
    FIRST_NAME CHAR(25),
    LAST_NAME CHAR(25),
    AGE INTEGER
);

CREATE TABLE FOOD (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    NAME CHAR(25),
    TYPE CHAR(25),
    DESCRIPTION CHAR(25),
    TIMESTAMP CHAR(25),
    USER INTEGER,
    FOREIGN KEY(USER) REFERENCES USER(ID)
);

CREATE TABLE MOOD (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    NAME CHAR(25),
    RATING INTEGER,
    TIMESTAMP CHAR(25),
    USER INTEGER,
    FOOD INTEGER,
    FOREIGN KEY(USER) REFERENCES USER(ID)
    FOREIGN KEY(FOOD) REFERENCES FOOD(ID)
);

CREATE TABLE NOTIFICATION (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MESSAGE CHAR(25),
    TIME CHAR(25),
    USER INTEGER,
    FOREIGN KEY(USER) REFERENCES USER(ID)
);