/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserProfileUI;

import NavigationController.NavController;
import UserProfileController.ProfileController;
import java.awt.Color;
import java.awt.Dimension;
/**
 *
 * @author Jake
 */
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class profilePanel extends javax.swing.JPanel {
    private final ProfileController profileCtrl;
    ArrayList<String> notifications = new ArrayList<String>();
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form profilePanel
     */
     @Override
    public Dimension getPreferredSize() {
        return new Dimension(360, 480);
    }
    public profilePanel(ProfileController profileCtrl) {
        this.profileCtrl = profileCtrl;
        initComponents();
        initComponents();
        for(int i =0; i < notifications.size();i++)
        {
            NotificationHistory.append(notifications.get(i)+"\n");
        }
        
        NotificationHistory.setEditable(false);
//        
//        usernameLabel.setFont(new Font("Helvetica", Font.CENTER_BASELINE, 16));
//        passwordLabel.setFont(new Font("Helvetica", Font.CENTER_BASELINE, 16));
//        ageLabel.setFont(new Font("Helvetica", Font.CENTER_BASELINE, 16));
        viewTab.setBackground(Color.LIGHT_GRAY);
        editTab.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        viewTab = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        editTab = new javax.swing.JPanel();
        editNameLabel = new javax.swing.JLabel();
        editNameButton = new javax.swing.JButton();
        editUsernameLabel = new javax.swing.JLabel();
        editUsernameButton = new javax.swing.JButton();
        editPasswordLabel = new javax.swing.JLabel();
        editPasswordButton = new javax.swing.JButton();
        editAgeLabel = new javax.swing.JLabel();
        editAgeButton = new javax.swing.JButton();
        notificationsTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotificationHistory = new javax.swing.JTextArea();
        notificationLabel = new javax.swing.JLabel();

        nameLabel.setText("Name: " + profileCtrl.getCurrUser().getFirstname() + " " + profileCtrl.getCurrUser().getLastname());

        usernameLabel.setText("Username: " + profileCtrl.getCurrUser().getUsername());

        passwordLabel.setText("Password: " + profileCtrl.getCurrUser().getPassword());

        ageLabel.setText("Age: " + String.valueOf(profileCtrl.currUser.getAge()));

        javax.swing.GroupLayout viewTabLayout = new javax.swing.GroupLayout(viewTab);
        viewTab.setLayout(viewTabLayout);
        viewTabLayout.setHorizontalGroup(
            viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTabLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewTabLayout.setVerticalGroup(
            viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(usernameLabel)
                .addGap(26, 26, 26)
                .addComponent(passwordLabel)
                .addGap(26, 26, 26)
                .addComponent(ageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Profile", viewTab);

        editNameLabel.setText("Name: " + profileCtrl.currUser.getFirstname()
            + " " + profileCtrl.currUser.getLastname());

        editNameButton.setText("Edit Name");
        editNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNameButtonActionPerformed(evt);
            }
        });

        editUsernameLabel.setText("Username: " + profileCtrl.currUser.getUsername());

        editUsernameButton.setText("Edit Username");
        editUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsernameButtonActionPerformed(evt);
            }
        });

        editPasswordLabel.setText("Password: " + profileCtrl.currUser.getPassword());

        editPasswordButton.setText("Edit Password");
        editPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasswordButtonActionPerformed(evt);
            }
        });

        editAgeLabel.setText("Age: " + String.valueOf(profileCtrl.currUser.getAge()));

        editAgeButton.setText("Edit Age");
        editAgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAgeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editTabLayout = new javax.swing.GroupLayout(editTab);
        editTab.setLayout(editTabLayout);
        editTabLayout.setHorizontalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(editNameLabel)
                        .addComponent(editUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(editPasswordLabel)
                    .addComponent(editAgeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editUsernameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editAgeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editPasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        editTabLayout.setVerticalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNameLabel)
                    .addComponent(editNameButton))
                .addGap(18, 18, 18)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUsernameLabel)
                    .addComponent(editUsernameButton))
                .addGap(18, 18, 18)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPasswordButton)
                    .addComponent(editPasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAgeLabel)
                    .addComponent(editAgeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Profile", editTab);

        NotificationHistory.setColumns(20);
        NotificationHistory.setRows(5);
        jScrollPane1.setViewportView(NotificationHistory);

        notificationLabel.setText("Notifications");

        javax.swing.GroupLayout notificationsTabLayout = new javax.swing.GroupLayout(notificationsTab);
        notificationsTab.setLayout(notificationsTabLayout);
        notificationsTabLayout.setHorizontalGroup(
            notificationsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationsTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(notificationsTabLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(notificationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        notificationsTabLayout.setVerticalGroup(
            notificationsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Notifications", notificationsTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNameButtonActionPerformed

    private void editUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsernameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUsernameButtonActionPerformed

    private void editPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPasswordButtonActionPerformed

    private void editAgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAgeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAgeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea NotificationHistory;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton editAgeButton;
    private javax.swing.JLabel editAgeLabel;
    private javax.swing.JButton editNameButton;
    private javax.swing.JLabel editNameLabel;
    private javax.swing.JButton editPasswordButton;
    private javax.swing.JLabel editPasswordLabel;
    private javax.swing.JPanel editTab;
    private javax.swing.JButton editUsernameButton;
    private javax.swing.JLabel editUsernameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JPanel notificationsTab;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel viewTab;
    // End of variables declaration//GEN-END:variables
}
