 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import NavigationController.NavController;

/**
 *
 * @author Jake
 */
public class AnalyticalMenuUI extends javax.swing.JFrame {
    private NavController navCtrl;
    private AnalyticMainMenuPanel analyticalMenu;
    
    
    public AnalyticalMenuUI(NavController navCtrl) {
        System.out.println("AnalyticMenuU Class Instantiated.");
        analyticalMenu = new AnalyticMainMenuPanel(navCtrl);
        this.setBounds(0, 0, 500, 500);
        this.setTitle("Food Mood Analytic");
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        this.add(analyticalMenu);
        this.setVisible(true); 
        initComponents();
        this.navCtrl = navCtrl; 
      }
    
    public void removeMainPanel(){
        this.remove(analyticalMenu);
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        historyMenuItem = new javax.swing.JMenuItem();
        correlationMenuItem = new javax.swing.JMenuItem();
        chartMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setText("FoodMood Analytic");

        historyMenuItem.setText("History");
        historyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyMenuItemActionPerformed(evt);
            }
        });
        menu.add(historyMenuItem);

        correlationMenuItem.setText("Correlation");
        correlationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correlationMenuItemActionPerformed(evt);
            }
        });
        menu.add(correlationMenuItem);

        chartMenuItem.setText("Chart");
        chartMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartMenuItemActionPerformed(evt);
            }
        });
        menu.add(chartMenuItem);

        MenuBar.add(menu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyMenuItemActionPerformed
        navCtrl.switchToHistoryCntrl();
    }//GEN-LAST:event_historyMenuItemActionPerformed

    private void correlationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correlationMenuItemActionPerformed
        navCtrl.switchToCorrelationCntrl();
    }//GEN-LAST:event_correlationMenuItemActionPerformed

    private void chartMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartMenuItemActionPerformed
        navCtrl.switchToChartCntrl();
    }//GEN-LAST:event_chartMenuItemActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem chartMenuItem;
    private javax.swing.JMenuItem correlationMenuItem;
    private javax.swing.JMenuItem historyMenuItem;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables
}
