/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import NavigationController.NavController;

/**
 *
 * @author Jake
 */
public class AppSelectionPanel extends javax.swing.JPanel {
    private NavController navCtrl;
    
    /**
     * Creates new form AppSelectionPanel
     * @param navCtrl
     */
    public AppSelectionPanel(NavController navCtrl) {
        this.navCtrl = navCtrl;
        initComponents();
        this.setSize(400, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        platformLabel = new javax.swing.JLabel();
        MobileButton = new javax.swing.JButton();
        AnalyticButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        platformLabel.setText("Choose A Platform:");

        MobileButton.setText("Mobile App");
        MobileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileButtonActionPerformed(evt);
            }
        });

        AnalyticButton.setText("Analytical App");
        AnalyticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MobileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnalyticButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(platformLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(platformLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MobileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnalyticButton)
                .addGap(138, 138, 138))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MobileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileButtonActionPerformed
        // TODO add your handling code here:
        navCtrl.switchToMobileMenu();
    }//GEN-LAST:event_MobileButtonActionPerformed

    private void AnalyticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticButtonActionPerformed
        // TODO add your handling code here:
        navCtrl.switchToAnalyticMenu();
    }//GEN-LAST:event_AnalyticButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticButton;
    private javax.swing.JButton MobileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel platformLabel;
    // End of variables declaration//GEN-END:variables
}
