/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import NavigationController.NavController;

/**
 *
 * @author Jake
 */
public class AppSelectionPanel extends javax.swing.JPanel {
    private NavController navCtrl;
    
    /**
     * Creates new form AppSelectionPanel
     * @param navCtrl
     */
    public AppSelectionPanel(NavController navCtrl) {
        this.navCtrl = navCtrl;
        initComponents();
        this.setSize(400, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        platformLabel = new javax.swing.JLabel();
        MobileButton = new javax.swing.JButton();
        AnalyticButton = new javax.swing.JButton();

        platformLabel.setText("Choose a platform:");

        MobileButton.setText("Mobile App");
        MobileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileButtonActionPerformed(evt);
            }
        });

        AnalyticButton.setText("Analytical App");
        AnalyticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(platformLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MobileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AnalyticButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(platformLabel)
                .addGap(36, 36, 36)
                .addComponent(MobileButton)
                .addGap(18, 18, 18)
                .addComponent(AnalyticButton)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MobileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileButtonActionPerformed
        // TODO add your handling code here:
        navCtrl.switchToMobileMenu();
    }//GEN-LAST:event_MobileButtonActionPerformed

    private void AnalyticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticButtonActionPerformed
        // TODO add your handling code here:
        navCtrl.switchToAnalyticMenu();
    }//GEN-LAST:event_AnalyticButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticButton;
    private javax.swing.JButton MobileButton;
    private javax.swing.JLabel platformLabel;
    // End of variables declaration//GEN-END:variables
}
