/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import NavigationController.NavController;
import java.awt.Font;

/**
 *
 * @author Jake
 */
public class MainMenuPanel extends javax.swing.JPanel {

     NavController navCtrl;
    /**
     * Creates new form MainMenuUI
     * @param navCtrl
     */
    public MainMenuPanel(NavController navCtrl) {
        //super(parent, modal);
        this.navCtrl = navCtrl; 
        initComponents();
        welcomeLabel.setFont(new Font("Helvetica", Font.CENTER_BASELINE, 16));
        optionLabel.setFont(new Font("Helvetica", Font.CENTER_BASELINE, 16));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodButton = new javax.swing.JButton();
        MoodButton = new javax.swing.JButton();
        userProfileButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        optionLabel = new javax.swing.JLabel();

        foodButton.setText("Food");
        foodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodButtonActionPerformed(evt);
            }
        });

        MoodButton.setText("Mood");
        MoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoodButtonActionPerformed(evt);
            }
        });

        userProfileButton.setText("User Profile");
        userProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfileButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setText("Welcome to Food Mood!");

        optionLabel.setText("Please select an option:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(MoodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionLabel)
                .addGap(47, 47, 47)
                .addComponent(foodButton)
                .addGap(37, 37, 37)
                .addComponent(MoodButton)
                .addGap(39, 39, 39)
                .addComponent(userProfileButton)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoodButtonActionPerformed

    private void userProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfileButtonActionPerformed
        navCtrl.switchToProfileCntrl();
    }//GEN-LAST:event_userProfileButtonActionPerformed

    private void foodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodButtonActionPerformed
        // TODO add your handling code here:
        navCtrl.switchToFoodCntrl();
    }//GEN-LAST:event_foodButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MoodButton;
    private javax.swing.JButton foodButton;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JButton userProfileButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
