/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CorrelationUI;

import CorrelationController.CorrelationController;
import FoodModel.Food;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tylerperdue
 */
public class CorrelationPanel extends javax.swing.JPanel {

    private CorrelationController correlationCtrl;
    
    /**
     * Creates new form CorrelationPanel
     */
    public CorrelationPanel(CorrelationController correlationCtrl) {
        this.correlationCtrl = correlationCtrl;
        initComponents();
        readFoodNameCorrelations();
        readFoodTypeCorrelations();
    }
    
    public void readFoodNameCorrelations() {
        try {
            ArrayList<ArrayList> foodNameCorrelations = correlationCtrl.getFoodNameCorrelations();
            DefaultTableModel model = (DefaultTableModel) foodNameCorrelationTable.getModel();
            model.getDataVector().removeAllElements();
            model.setColumnIdentifiers(new String[]{"Food", "Mood", "Strength"});
            for (int i = 0; i < foodNameCorrelations.size(); i++) {
                ArrayList<String> correlation = foodNameCorrelations.get(i);
                String[] data = {correlation.get(0), correlation.get(1), correlation.get(2)};
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error has occurred in CorrelationPanel - readFoodNameCorrelations(): " + e);
        }
    }
    
    public void readFoodTypeCorrelations() {
        try {
            ArrayList<ArrayList> foodTypeCorrelations = correlationCtrl.getFoodTypeCorrelations();
            DefaultTableModel model = (DefaultTableModel) foodTypeCorrelationTable.getModel();
            model.getDataVector().removeAllElements();
            model.setColumnIdentifiers(new String[]{"Food Type", "Mood", "Strength"});
            for (int i = 0; i < foodTypeCorrelations.size(); i++) {
                ArrayList<String> correlation = foodTypeCorrelations.get(i);
                String[] data = {correlation.get(0), correlation.get(1), correlation.get(2)};
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error has occurred in CorrelationPanel - readFoodTypeCorrelations(): " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        foodNameCorrelationLbl = new javax.swing.JLabel();
        foodTypeCorrelationLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTypeCorrelationTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodNameCorrelationTable = new javax.swing.JTable();

        titleLbl.setText("Correlations");

        foodNameCorrelationLbl.setText("Food");

        foodTypeCorrelationLbl.setText("Food Type");

        foodTypeCorrelationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(foodTypeCorrelationTable);

        foodNameCorrelationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(foodNameCorrelationTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(foodTypeCorrelationLbl)
                            .addComponent(foodNameCorrelationLbl)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(titleLbl)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodNameCorrelationLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(foodTypeCorrelationLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foodNameCorrelationLbl;
    private javax.swing.JTable foodNameCorrelationTable;
    private javax.swing.JLabel foodTypeCorrelationLbl;
    private javax.swing.JTable foodTypeCorrelationTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
